#检查磁盘空间

name: check-space

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@main
    
    - name: Check space usage
      if: (!cancelled())
      run: df -hT
